import random
import pytest
import string
from cranio.core import SessionMeta
from cranio.app.dialogs import MeasurementDialog, SessionMetaPromptWidget

def test_MeasurementDialog_set_and_get_distractor_index():
    d = MeasurementDialog()
    
    # integers
    for i in range(20):
        d.distractor_index = i
        assert d.distractor_index == i
    
    # floats
    for _ in range(20):
        i = random.random()
        with pytest.raises(ValueError):
            d.distractor_index = i
            
    # characters
    for s in string.printable:
        with pytest.raises(ValueError):
            d.distractor_index = s
            
def test_SessionMetaPromptWidget_patient_session_meta():
    w = SessionMetaPromptWidget()
    # session is autogenerated
    assert w.session is not None
    assert type(w.session) == str
    # session cannot be changed
    assert not w.session_widget.isEnabled()
    with pytest.raises(AttributeError):
        w.session = 'foo'
    w.patient = 'foo'
    assert w.patient == 'foo'
    assert SessionMeta(w.patient, w.session) == w.session_meta
    