import enum
from contextlib import contextmanager
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy import Column, Integer, String, DateTime, Float, Boolean, Enum, ForeignKey, create_engine
from cranio.core import generate_unique_id
from cranio import __version__

# define database connection
# TODO: replace in-memory database
#engine = create_engine(f'sqlite:///{DATABASE_NAME}.db')
engine = create_engine('sqlite://')
Base = declarative_base()
SQLSession = sessionmaker(bind=engine)


@contextmanager
def session_scope():
    ''' Provide a transactional scope around a series of operations. '''
    session = SQLSession()
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()


class Patient(Base):
    __tablename__ = 'dim_patient'
    id = Column(String, primary_key=True, comment='Patient identifier (pseudonym)')


class Session(Base):
    __tablename__ = 'dim_session'
    id = Column(String, primary_key=True, default=generate_unique_id,
                comment='Autogenerated session identifier (UUID v1)')
    patient_id = Column(String, ForeignKey('dim_patient.id'), nullable=False)
    started_at = Column(DateTime, comment='Session start (i.e., software launch) date and time')
    sw_version = Column(String, default=__version__)


class Document(Base):
    __tablename__ = 'dim_document'
    id = Column(String, primary_key=True, default=generate_unique_id,
                comment='Autogenerated document identifier (UUID v1)')
    session_id = Column(String, ForeignKey('dim_session.id'), nullable=False)
    distractor_id = Column(Integer, comment='Distractor identifier (e.g., 1 or 2)')
    started_at = Column(DateTime, comment='Data collection start date and time')
    operator = Column(String, comment='Person responsible for the distraction')
    notes = Column(String, comment='User notes')
    distraction_achieved = Column(Float, comment='Achieved distraction in millimeters')
    missed_distractors = Column(String, comment='Comma-separated list of missed distractor identifiers')
    distraction_plan_followed = Column(Boolean, comment='Boolean indicating if the distraction plan was followed')


class Measurement(Base):
    __tablename__ = 'fact_measurement'
    id = Column(Integer, primary_key=True, autoincrement=True)
    document_id = Column(String, ForeignKey('dim_document.id'), nullable=False)
    time_s = Column(Float, nullable=False, comment='Time since start of data collection in seconds')
    torque_Nm = Column(Float, nullable=False, comment='Torque measured from the screwdriver')
    event_id = Column(Float, nullable=True, comment='Manually annotated distraction event identifier')


class LogLevel(enum.Enum):
    DEBUG = 0
    INFO = 1
    ERROR = 2


class Log(Base):
    ''' Software log table '''
    __tablename__ = 'fact_log'
    id = Column(Integer, primary_key=True, autoincrement=True)
    document_id = Column(String, ForeignKey('dim_document.id'), nullable=False)
    datetime = Column(DateTime, nullable=False, comment='Log entry date and time')
    level = Column(Enum(LogLevel), nullable=False, comment='Log entry level')
    message = Column(String, nullable=False, comment='Log entry')


# create database schema
Base.metadata.create_all(engine)


def export_schema_graph(name: str):
    '''
    Export schema graph as a .png image.
    NOTE: Requires Graphviz (download from http://www.graphviz.org/download/)
    '''
    from sqlalchemy_schemadisplay import create_schema_graph
    graph = create_schema_graph(metadata=Base.metadata, show_datatypes=False, show_indexes=False,
                                rankdir='TB', concentrate=False)
    graph.write_png(name)
